### ISSUE TITLE
Max Grimoire is incorrect for Playstation

### ISSUE THREAD

**Issue by bradchoate** [TrackerNetwork/DestinyStatus#54] opened 2016-12-27 22:18 UTC
Should be 5545, not 5540. Here's a case where a user is just short by 5 points but the Grimoire page says they're at "5540 / 5540": http://destinystatus.com/psn/indie_cat/grimoire

**Comment by iBotPeaches** [comment] 2016-12-28 12:08
This is a far more difficult problem than on the surface. See the comment I wrote here in #34 - https://github.com/TrackerNetwork/DestinyStatus/issues/34#issuecomment-184673099

If we can figure out what cards are rewarding points that shouldn't, then we can align DestinyStatus, but short of starting a new profile and recording every Grimoire card unlocked this is just an unfortunate bug until the Bungie API updates and corrects itself or we find the cards that say 0 points in the API, but actually reward points.

Closing as duplicate of #34 and nothing we can really do right now.

**Closed as completed by iBotPeaches** 2016-12-28 12:08 UTC
Labels: duplicate
